
name: Kudos for Code
on:
  push:
    branches: ["kudos"]
  workflow_dispatch:

jobs:
  get-packages:
    name: Get Monorepo Packages
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-dirs.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
        with:
          fetch-depth: 0
      - name: Set packages
        id: set-dirs
        run: |
          echo "Before: ${{ github.event.before }}"
          echo "SHA: ${{ github.sha }}"
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          packages=$(echo "${changed_files}" | grep '^packages/' | cut -d'/' -f2-3 | sort -u)

          # Convert packages to a matrix format
          matrix=$(echo "${packages}" | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=matrix::${matrix}"
  kudos:
    needs: get-packages
    name: Semicolons Kudos
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix: 
        directory: ${{fromJson(needs.get-packages.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - uses: LoremLabs/kudos-for-code-action@latest
        with:
          search-dir: ${{ matrix.directory }}
          destination: "artifact"
          generate-nomerges: true
          generate-validemails: true
          generate-limitdepth: 1
          generate-fromrepo: true
          analyze-repo: true
          skip-ids: ""
